<?php

use Leanpay\Payment\Api\Data\InstallmentInterface;
use Leanpay\Payment\Block\Installment\Pricing\Render\DefaultPriceBox;
use Leanpay\Payment\Helper\InstallmentHelper;
use Magento\Framework\Escaper;

/** @var DefaultPriceBox $block */

$price = $block->getLowestInstallmentPrice();
$viewKey = $block->getData('view_key') ?? InstallmentHelper::LEANPAY_INSTALLMENT_VIEW_OPTION_PRODUCT_PAGE;
$helper = $block->getInstallmentHelper();
$canShow = $helper->canShowInstallment($viewKey);
$fontSize = $helper->getFontSize($viewKey);
$color = $helper->getInstallmentColor();
?>
<?php if ($viewKey !== InstallmentHelper::LEANPAY_INSTALLMENT_VIEW_OPTION_PRODUCT_PAGE): ?>
    <?php if ($price && $canShow): ?>
        <div class="installment-price"
             style="color: <?= $block->escapeHtmlAttr($color) ?>;
                 font-size: <?= $block->escapeHtmlAttr($fontSize)?>px;">
            <?= $block->escapeHtml($helper->getCategoryPriceBlock($block->getAmount())); ?>
        </div>
    <?php endif; ?>
<?php else: ?>
    <?php if ($price && $canShow): ?>
        <div class="installment-wrapper" data-mage-init='{"Leanpay_Payment/js/installment":""}'>
            <span class="installment-wrapper-start"><?= $block->escapeHtml(__('ali')); ?></span>
            <div class="installment-additional-wrapper" style="font-size: <?= /* @noEscape */ $fontSize ?>px;">
                <div class="installment-plans">
                    <div class="installment-block-wrapper">
                        <?php $list = $helper->getInstallmentList($block->getAmount()); ?>
                        <span class="installment-block">
                            <?= $block->escapeHtml(__($helper->getTranslation('Hitro in enostavno obročno odplačevanje'))); ?>
                        </span>
                        <span class="installment-min-price">
                        <span class="installment-price"
                              style="background-color:<?= $block->escapeHtmlAttr($helper->getBackgroundColor()); ?>;">
                            <?= $block->escapeHtml(__($helper->getTranslation('Že od'))); ?>
                            <strong>
                                <?= $block->escapeHtml($helper->getProductPriceBlock($block->getAmount()));?>
                            </strong>
                        </span>
                        <span class="installment-message"
                              style="border: 1px solid <?= $block->escapeHtmlAttr($helper->getBackgroundColor()) ?>;">
                            <?= $block->escapeHtml(__($helper->getTranslation('Vaš mesečni obrok'))); ?>
                        </span>
                    </div>
                </div>
                <div class="installment-mouse">
                    <div class="installment-info">
                        <?php if ($helper->allowDownPayment()): ?>
                        <div class="installment-deposit">
                            <span class="deposit">
                                <?= $block->escapeHtml(
                                    __('+ %1 € polog', $helper->getDownPaymentRule($block->getAmount()))
                                ); ?>
                            </span>
                        </div>
                        <?php endif;?>
                        <div class="installment-logo-wrapper">
                            <span class="installment-logo-text">
                                <?= $block->escapeHtml(__($helper->getTranslation('Izračun obrokov'))); ?>
                            </span>
                            <span class="installment-logo-span">
                                <img class="installment-logo"
                                     src="<?= /* @noEscape */ $block->getLogo(); ?>"
                                     alt="leapay-logo"/>
                            </span>
                        </div>
                    </div>
                    <div class="installment-tooltip hidden">
                        <div class="installment-title">
                            <img class="installment-logo"
                                 src="<?= /* @noEscape */ $block->getLogo(); ?>"
                                 alt="leapay-logo"/>
                        </div>
                        <div class="installment-plans">
                            <div class="installment-lowest-amount">
                                <?php if ($helper->shouldRenderTooltipPriceBlock($block->getAmount(), true)): ?>
                                    <span class="installment-lowest-message">
                                     <?= $block->escapeHtml(__($helper->getTranslation('Želim čim nižji obrok'))); ?>
                                    <strong><?= $block->escapeHtml($helper->getTooltipPriceBlock($block->getAmount(), true)); ?></strong>
                                    </span>
                                <?php endif; ?>
                            </div>
                            <div class="installment-lowest-term">
                                <?php if ($helper->shouldRenderTooltipPriceBlock($block->getAmount(), false)): ?>
                                    <span class="installment-lowest-message">
                                        <?= $block->escapeHtml(__($helper->getTranslation('Odplačati želim čim prej'))); ?>
                                        <strong><?= $block->escapeHtml($helper->getTooltipPriceBlock($block->getAmount(), false)); ?></strong>
                                    </span>
                                <?php endif; ?>
                            </div>
                            <div class="installment-slider-term">
                                <div class="term-text">
                                    <?= $block->escapeHtml(__($helper->getTranslation('Želim si izbrati svoje obroke'))); ?>
                                </div>
                                <div class="term-html">
                                    <span class="installment_period">
                                    </span>
                                    <span class="installment_amount"></span>
                                </div>
                                <div class="installment-slider"></div>
                                <div class="total-html">
                                    <span><?= $block->escapeHtml(__($helper->getTranslation('Informativni znesek za plačilo'))); ?></span>
                                    <span class="total"></span>
                                </div>
                            </div>
                        </div>
                        <div class="installment-quick-information">
                            <?= $block->escapeHtml(
                                __($helper->getTranslation('Leanpay omogoča hitro in enostavno obročno odplačevanje preko spleta. ').
                                    $helper->getTranslation('Za obročno plačilo v košarici izberi Leanpay. '))
                            ); ?>
                        </div>
                        <div class="installment-links">
                            <a href="<?= $block->escapeUrl($helper->getCheckYourLimitURL()); ?>"
                               target="_blank"
                               rel="noopener noreferrer">
                                <span class="link-option"><?= $block->escapeHtml(__($helper->getTranslation('Preveri svoj limit'))); ?></span>
                            </a>
                            <a href="<?= $block->escapeUrl($helper->getMoreInfoURL()); ?>"
                               target="_blank"
                               rel="noopener noreferrer">
                                <span class="link-option"><?= $block->escapeHtml(__($helper->getTranslation('Več informacij'))); ?></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="installment-slider-data" style="display: none; visibility: hidden;">
            <?= $helper->getJsonConfig($block->getAmount()) ?: ''; ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
