<?php

use Leanpay\Payment\Block\Installment\Pricing\Render\DefaultPriceBox;
use Magento\Framework\Escaper;

/** @var DefaultPriceBox $block */
/** @var Escaper $escaper */

$theme = $block->getInstallmentHelper()->getColorTheme();
?>
<style>
    .installment-wrapper,
    .installment-price.plp-installment {
        --lp-text-primary: <?= $escaper->escapeHtml($theme['text_primary']) ?>;
        --lp-text-secondary: <?= $escaper->escapeHtml($theme['text_secondary']) ?>;
        --lp-text-dropdown: <?= $escaper->escapeHtml($theme['text_dropdown']) ?>;
        --lp-text-price: <?= $escaper->escapeHtml($theme['text_price']) ?>;
        --lp-text-link: <?= $escaper->escapeHtml($theme['text_link']) ?>;
        --lp-bg-primary: <?= $escaper->escapeHtml($theme['bg_primary']) ?>;
        --lp-bg-secondary: <?= $escaper->escapeHtml($theme['bg_secondary']) ?>;
        --lp-bg-dropdown: <?= $escaper->escapeHtml($theme['bg_dropdown']) ?>;
        --lp-bg-soft: <?= $escaper->escapeHtml($theme['bg_soft']) ?>;
    }
</style>
