<script>
    require([
        'jquery',
        'Leanpay_Payment/js/form',
        'domReady!'
    ], function ($, form) {
        $(document).ready(function () {

            $(document).on('click', 'div[data-index="leanpay-promotions"]', function() {
                form.showHideAttr();
            });

            $(document).on('change', '[name="product[leanpay_product_time_based]"]', function() {
                form.showHideAttr();
            });
            form.showHideAttr();
        });
    });
</script>
